spring.application.name=teamproject
# ==========================================
# Redis 연결 설정
# ==========================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================================
# 한국투자증권 (KIS) API 설정
# ==========================================
# 실전투자용 URL
kis.api.url=https://openapi.koreainvestment.com:9443
kis.api.app-key=
kis.api.app-secret=

# ==========================================
# Oracle DB 연결 설정
# ==========================================
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 일반적인 오라클 XE 버전의 로컬 주소입니다. 
# (만약 포트가 1521이 아니거나 이름이 XE가 아니면 본인 환경에 맞게 수정!)
spring.datasource.url=jdbc:oracle:thin:@teacherdev09.kro.kr:8877:xe

# ⭐️ 여기에 본인이 생성한 오라클 계정 아이디와 비밀번호를 적어주세요!
spring.datasource.username=team12
spring.datasource.password=12345

# ==========================================
# JPA (Hibernate) 편리한 설정
# ==========================================
# 콘솔에 JPA가 날리는 SQL 쿼리를 예쁘게 보여줍니다.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Entity 클래스를 만들면 오라클 DB에 자동으로 테이블을 생성해 줍니다! (실무에선 validate 추천)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.dialect.oracle_version=11