# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: backend CI

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Create secrets.properties
      run: |
        mkdir -p src/main/resources

        echo "kis.api.app-key=${{ secrets.KIS_API_KEY }}" > src/main/resources/secrets.properties
        echo "kis.api.app-secret=${{ secrets.KIS_API_SECRET }}" >> src/main/resources/secrets.properties
        echo "spring.data.redis.password=${{ secrets.REDIS_PASSWORD }}" >> src/main/resources/secrets.properties
        echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> src/main/resources/secrets.properties
        echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> src/main/resources/secrets.properties
        echo "recaptcha.secret=${{ secrets.RECAPTCHA_SECRET }}" >> src/main/resources/secrets.properties
        echo "google.oauth.client-id=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> src/main/resources/secrets.properties
        
    - name: Verify secrets.properties creation
      run: |
        echo ">>> Project Root Directory:"
        ls -F
        echo ">>> Resources Directory Structure:"
        ls -R src/main/resources
        echo ">>> Checking if secrets.properties exists:"
        if [ -f src/main/resources/secrets.properties ]; then
          echo "SUCCESS: secrets.properties found."
        else
          echo "ERROR: secrets.properties NOT FOUND!"
          exit 1
        fi
        
        echo ">>> Current Directory:"
        pwd
        echo ">>> Resources Directory Listing:"
        ls -R src/main/resources
    - name: Build with Maven
      run: |
        mvn -B package -DskipTests --file pom.xml
        echo ">>> Target Directory Listing:"
        ls -R target

#test